version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=secret
      - MONGO_HOST=mongodb
    # command: ["tail", "-f", "/dev/null"]
